# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 950efd87a4c84ff3f2e154b3966623269fd4d2c5b16c3510dc4398a3cc4a552babf1248c93429b4c348338753ab21194201566cf41258007eccbb090272072ac

test:
  secret_key_base: 6a03a20ffcf6241ab1c6d380c1418a94402d548cb1297c5abd4dfc4ec529fb0c22437bb2a9b72e118ef0ea5cd7758bf182c7721eeac2adaae6cae57785821b84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
